run:
  deadline: 1m
  tests: false
  skip-files:
    - "testing.go"
    - ".*\\.pb\\.go"
    - ".*\\.gen\\.go"

linters-settings:
  golint:
    min-confidence: 0
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 4
  misspell:
    locale: US
  revive:
    rules:
      - name: var-naming
        disabled: true

linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goerr113
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomodguard
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
